### ISSUE TITLE
Inconsistent window drop shadow

### ISSUE THREAD

**Issue by GordianZ** [lujjjh/lito#1]
Side+bottom drop shadows are visibly harsher than the top border.

![image](https://user-images.githubusercontent.com/462272/133968183-9864b384-122b-426a-97b5-479763be0e35.png)

**Comment by lujjjh** [comment]
<img src="https://user-images.githubusercontent.com/3000535/134015567-3b37dbc1-b479-4639-9227-26d99371e055.png" width="421" />

Unable to reproduce this issue on Windows 10. Could you please check other apps such as Windows Explorer and see if those windows' shadows render correctly?

**Comment by lujjjh** [comment]
I've reproduced this issue and this seems to be a side effect of side bar blur behind.

I'm currently removing side bar blur behind since it uses an undocumented Windows API and needs more investigations.
