### ISSUE TITLE
[issue] Unable to load lyrics 404

### ISSUE THREAD

**Issue by HueLiu** [lujjjh/lito#11]
musickit.js:15918 
        
       GET https://amp-api.music.apple.com/v1/catalog/cn/songs/1460622491/lyrics 404

![image](https://user-images.githubusercontent.com/19755727/134806668-5ec3e113-b49e-4f90-8a0d-a70125c81b5b.png)

I'm using HK Apple Music, but the loading of lyrics seems to be in CN area, I'm not sure if this is the reason

Logs: [app.example-1632657282153.log](https://github.com/lujjjh/lito/files/7231318/app.example-1632657282153.log)

**Comment by lujjjh** [comment]
Thank you for your feedback! I'll fix it soon.

**Comment by lujjjh** [comment]
Could you please try [LitoMusic.exe](https://github.com/lujjjh/lito/suites/3876066800/artifacts/96466129) from [this build](https://github.com/lujjjh/lito/actions/runs/1275330561) and see if it has fixed this issue?

**Comment by HueLiu** [comment]
It works now :D
