### ISSUE TITLE
Want to add icons to the Windows tray

### ISSUE THREAD

**Issue by EndDream** [lujjjh/lito#16]
In the current version, a blank icon is displayed in the Windows tray, which often makes me mistakenly believe that the software is closed.
![图片](https://user-images.githubusercontent.com/43370659/135946053-5cc9a164-3767-4f73-99d7-f1df142a230d.png)

**Comment by lujjjh** [comment]
Thank you for your feedback.

This should have been fixed in [v0.1.0.0-beta.9](https://github.com/lujjjh/lito/releases/tag/v0.1.0.0-beta.9).

**Comment by EndDream** [comment]
Thanks, I can already see the icon in the tray
