### ISSUE TITLE
[Issue] 艺人访谈 is missing

### ISSUE THREAD

**Issue by HueLiu** [lujjjh/lito#19]
In Browse and Radio,The content of  艺人访谈 cannot be loaded.

![image](https://user-images.githubusercontent.com/19755727/136657665-c5066a6d-05e7-49a8-be7b-f66ea72bc26a.png)

## log file
[app.example-1633782274987.log](https://github.com/lujjjh/lito/files/7315555/app.example-1633782274987.log)

**Comment by lujjjh** [comment]
Videos are not supported for now. I'll see how to filter them out.
